### ISSUE TITLE
Trouble connecting to API

### ISSUE THREAD

**Issue by Kansas-Guy** [justein230/BbApiConnector-Python#2]
I've followed the instructions you have included, but I'm getting a 404 error and AttributeError: 'NoneType' object has no attribute 'get' when I try to start a session.

I've gone through the authentication process twice to obtain new tokens to check if I copied them incorrectly, but that didn't resolve the issue.

Below is the code that I'm using to start the session. 

Sorry if this isn't the best way to talk about my issue. This is the first time that I have used Github.

from BbApiConnector import BbApiConnector

api_conn = BbApiConnector('app_secrets.json')

bb_session = api_conn.get_session()

params = {
    'event_id': '11'
}

req = bb_session.get('https://api.sky.blackbaud.com/event/v1/events', params = params)

**Comment by justein230** [comment]
It seems like this is because the API you are connecting to does not need information in the body of the request, but rather in the URL. You could use an f-string to put the variable in the URL (endpoint reference [here](https://developer.sky.blackbaud.com/docs/services/event/operations/GetEvent)):

```
event_id = 11
bb_session.get(f'https://api.sky.blackbaud.com/event/v1/events/{event_id}')
```

In the future, please use the code-block formatting tool to format your example code as code, so that it is easier to read.

**Comment by Kansas-Guy** [comment]
I tried using f-string like you suggested (full code below), but still am receiving the same Attribute error and this printed out: {"statusCode":404,"message":"Resource not found","status":404,"title":"Resource not found"}

```
from BbApiConnector import BbApiConnector

api_conn = BbApiConnector('app_secrets.json')

bb_session = api_conn.get_session()

event_id = 11
bb_session.get(f'https://api.sky.blackbaud.com/event/v1/events/{event_id}')
```

Did I potentially incorrectly set up my tokens? Those steps went smooth, so not sure where I'm messing up.

Thanks for the help.

**Comment by justein230** [comment]
Try the SKY API console and see if you get anything: https://developer.sky.blackbaud.com/docs/services/event/operations/GetEvent. If you get an error there, it's an error with your call.

**Comment by justein230** [comment]
Also try changing `event_id` to a string by putting quotes around it. The API console says it needs to take in a string

**Comment by Kansas-Guy** [comment]
I went through the process to grab another access token through the steps to grab an access token using bb_auth.py. Then I used that token for the authorization header on the SKY API portal. Successfully connected that way.

So I used my new access and refresh tokens to update them accordingly in necessary files. I also hard-coded the request url to remove the possibility of the variable and f-string throwing an error. This is what the code I ran:

```
api_conn = BbApiConnector('app_secrets.json')

bb_session = api_conn.get_session()

bb_session.get('https://api.sky.blackbaud.com/event/v1/events/11')
```

I still received 'AttributeError: 'NoneType' object has no attribute 'get'.

Is there another piece of code or information that I should pass along to help figure out what I'm doing incorrectly?

Thanks for the continued help.

**Comment by Kansas-Guy** [comment]
I believe I figured out my issue.

After looking more at what has happening when I called 

```
bb_session = api_conn.get_session()
```
I realized that my test_api_endpoint url was incomplete. Once I corrected that issue I successfully connected and have started accessing endpoints.

Apologies for taking up your time. I'll close out the issue.
